name: raylib_dart
description: raylib is a simple and easy-to-use library to enjoy videogames programming.
version: 0.4.0
homepage: https://github.com/insinfo/raylib_dart

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  ffi: ^2.1.0 

dev_dependencies:
  ffigen: ^10.0.0
  test: ^1.22.0
  #very_good_analysis: ^2.4.0

ffigen:
  name: Raylib
  description: Bindings to Raylib
  output: lib/src/generated_bindings.dart
  llvm-path:
    - C:/llvm
  comments:
    style: any
    length: full
  headers:
    entry-points:
      - C:/MyProjectsDart/dart-raylib/include_4.2/raylib.h
  enums:
    member-rename:
      '(.*)': 
          'KEY_(.*)': '$1'
          'GESTURE_(.*)': '$1'
          'MOUSE_BUTTON_(.*)': '$1'
          'CAMERA_(.*)': '$1'
          'BLEND_(.*)': '$1'
          'GAMEPAD_AXIS_(.*)': '$1'
          'GAMEPAD_BUTTON_(.*)': '$1'
          'FLAG_(.*)': '$1'
          'MOUSE_CURSOR_(.*)': '$1'
          'MATERIAL_MAP_(.*)': '$1'
          'SHADER_LOC_(.*)': '$1'
          'SHADER_UNIFORM_(.*)': '$1'
          'SHADER_ATTRIB_(.*)': '$1'
          'PIXELFORMAT_(.*)': '$1'
          'TEXTURE_FILTER_(.*)': '$1'
          'TEXTURE_WRAP_(.*)': '$1'
          'CUBEMAP_LAYOUT_(.*)': '$1'
          'FONT_(.*)': '$1'
          'NPATCH_(.*)': '$1'
          'LOG_(.*)': '$1'
